[config]
prefer = "saturation"

[templates.hyprland-borders]
input_path = "~/.config/matugen/templates/hyprland-borders.sh"
output_path = "~/.cache/matugen/hyprland-borders.sh"
post_hook = "bash ~/.cache/matugen/hyprland-borders.sh"
