hl.on("hyprland.start", function ()
    hl.exec_cmd("hyprctl setcursor Colloid-cursors 24")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("/home/utopia/.config/hypr/scripts/Polkit.sh")
    hl.exec_cmd("/home/utopia/.config/hypr/scripts/WallpaperDaemon.sh")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)
