#!/usr/bin/env bash
# Auto-generated by matugen — border colors from wallpaper
# KEY=hex lines below feed hyprland.lua; keep the format.
# ACTIVE1={{colors.primary.default.hex_stripped}}ee
# ACTIVE2={{colors.tertiary.default.hex_stripped}}ee
# ANGLE=45
# INACTIVE={{colors.outline_variant.default.hex_stripped}}aa
hyprctl eval 'hl.config({ general = { col = { active_border = { colors = {"rgba({{colors.primary.default.hex_stripped}}ee)", "rgba({{colors.tertiary.default.hex_stripped}}ee)"}, angle = 45 }, inactive_border = "rgba({{colors.outline_variant.default.hex_stripped}}aa)" } } })'
