#!/usr/bin/env bash
# Auto-generated by matugen — border colors from wallpaper
hyprctl eval 'hl.config({ general = { col = { active_border = { colors = {"rgba({{colors.primary.default.hex_stripped}}ee)", "rgba({{colors.tertiary.default.hex_stripped}}ee)"}, angle = 45 }, inactive_border = "rgba({{colors.outline_variant.default.hex_stripped}}aa)" } } })'
