# Gruvbox Material Dark (palette: material, background: medium)

# Default colors
[colors.primary]
background = '#282828'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Cursor & selection
[colors.cursor]
text     = '#282828'
cursor   = '#d4be98'

[colors.selection]
text       = '#d4be98'
background = '#665c54'
